version: '3.3'

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "8540:8540"
      - "8550:8550"
      - "8560:8560"
    volumes:
      # Hack to make this work from both docker/federation/ and docker/federation-test/
      - ../federation/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    depends_on:
      - lemmy_alpha
      - pictrs_alpha
      - lemmy_beta
      - pictrs_beta
      - lemmy_gamma
      - pictrs_gamma
      - iframely

  lemmy_alpha:
    image: lemmy-federation:latest
    environment:
      - LEMMY_HOSTNAME=lemmy_alpha:8540
      - LEMMY_DATABASE_URL=postgres://lemmy:password@postgres_alpha:5432/lemmy
      - LEMMY_JWT_SECRET=changeme
      - LEMMY_FRONT_END_DIR=/app/dist
      - LEMMY_FEDERATION__ENABLED=true
      - LEMMY_FEDERATION__TLS_ENABLED=false
      - LEMMY_FEDERATION__ALLOWED_INSTANCES=lemmy_beta,lemmy_gamma
      - LEMMY_PORT=8540
      - LEMMY_SETUP__ADMIN_USERNAME=lemmy_alpha
      - LEMMY_SETUP__ADMIN_PASSWORD=lemmy
      - LEMMY_SETUP__SITE_NAME=lemmy_alpha
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    depends_on:
      - postgres_alpha
  postgres_alpha:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_alpha:/var/lib/postgresql/data
  pictrs_alpha:
    image: asonix/pictrs:v0.1.13-r0
    user: 991:991
    volumes:
      - ./volumes/pictrs_alpha:/mnt

  lemmy_beta:
    image: lemmy-federation:latest
    environment:
      - LEMMY_HOSTNAME=lemmy_beta:8550
      - LEMMY_DATABASE_URL=postgres://lemmy:password@postgres_beta:5432/lemmy
      - LEMMY_JWT_SECRET=changeme
      - LEMMY_FRONT_END_DIR=/app/dist
      - LEMMY_FEDERATION__ENABLED=true
      - LEMMY_FEDERATION__TLS_ENABLED=false
      - LEMMY_FEDERATION__ALLOWED_INSTANCES=lemmy_alpha,lemmy_gamma
      - LEMMY_PORT=8550
      - LEMMY_SETUP__ADMIN_USERNAME=lemmy_beta
      - LEMMY_SETUP__ADMIN_PASSWORD=lemmy
      - LEMMY_SETUP__SITE_NAME=lemmy_beta
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    depends_on:
      - postgres_beta
  postgres_beta:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_beta:/var/lib/postgresql/data
  pictrs_beta:
    image: asonix/pictrs:v0.1.13-r0
    user: 991:991
    volumes:
      - ./volumes/pictrs_beta:/mnt

  lemmy_gamma:
    image: lemmy-federation:latest
    environment:
      - LEMMY_HOSTNAME=lemmy_gamma:8560
      - LEMMY_DATABASE_URL=postgres://lemmy:password@postgres_gamma:5432/lemmy
      - LEMMY_JWT_SECRET=changeme
      - LEMMY_FRONT_END_DIR=/app/dist
      - LEMMY_FEDERATION__ENABLED=true
      - LEMMY_FEDERATION__TLS_ENABLED=false
      - LEMMY_FEDERATION__ALLOWED_INSTANCES=lemmy_alpha,lemmy_beta
      - LEMMY_PORT=8560
      - LEMMY_SETUP__ADMIN_USERNAME=lemmy_gamma
      - LEMMY_SETUP__ADMIN_PASSWORD=lemmy
      - LEMMY_SETUP__SITE_NAME=lemmy_gamma
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    depends_on:
      - postgres_gamma
  postgres_gamma:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_gamma:/var/lib/postgresql/data
  pictrs_gamma:
    image: asonix/pictrs:v0.1.13-r0
    user: 991:991
    volumes:
      - ./volumes/pictrs_gamma:/mnt

  iframely:
    image: jolt/iframely:v1.4.3
    volumes:
      - ../iframely.config.local.js:/iframely/config.local.js:ro
